= Thesis draft all content

:stem: latexmath
:toc:

== Working topic
// Indoor local positioning system for smartphones with infrastructure-free integration.

// Development of localization and mapping system for indoor smartphone localization


// Implementation of spatial sensor measurements from smartphone's sensors to improve performance

// imp of magnetic field measurements in hybrid measurement model

Development of SLAM system
including loop closing, relocalization and map reuse
for
smartphone localization
with magnetic field measurments.


// Implementation of information in slam system to improve its performance.

// Clinical question: "In children with headache, is paracetamol more effective than placebo against pain?"

// * Population = Children with headaches; keywords = children + headache
// * Intervention = Paracetamol; keyword = paracetamol
// * Compared with = Placebo; keyword = placebo
// * Outcome of interest = Pain; keyword = pain

// * Population - localization / slam system
// * Intervention
// * Compared - traditional fingerprinting system
// * Outcome - better performance (accuracy * cost * ....)

{toc}

=== Background and problem statement



// that describes the subject matter in terms of its importance and potential for action. Describe the connection between research and innovation. Clarify the reasons for the choice of the thesis project topic.
//
// The scope:: Development of software system for indoor location services applications, with system properties (price, accuracy, features) being optimized for specific chosen user case.

// tag::example[]
// end::example[]

// tag::background_and_ps[]

The topic of the project is related to the problem of indoor navigation.
The context of the problem states that no GPS data are available at hand, which
makes the use of usual navigation services impossible.

Most existing systems of indoor navigation require special mapping stage.
Novel indoor navigation systems utilize the data recorded from users. This is what is called
the crowdsource approach.

For realtime indoor navigation, in conditions where is no initial data is available,
we have to pass stages of localization and mapping, which can be done simultaneously in SLAM approach.
We aim to combine both SLAM and crowdsource approach for the best performance of positioning system.

// Опишите связь между исследованиями и инновациями. Уточните причины выбора темы дипломного проекта.
The innovation of this research is in ability to provide same navigation services with less information and in more natural way, which means also the reduced cost of the system overall.

// We aim to delelop realtime

In indoor conditions we want to have a realtime localization system with no tradinional sensors (camera, LIDAR) and hardware (BLE beacons) used.
// Such system involving localization without any additional hardware and with measurements of only existsting spatial information are called infrastructure free.
The approach for localization without any additional hardware is called infrastructure free.
The common
In formulated case we don't use cameras and LIDARs for localization.

We want to have robust localizatoin system which can operate in this special conditions. For this reason we have to define a localization and mapping algorithm that will satisfy required performance.

// The scope of similar problems and solutions is
// literature review here
// compare with RSSI and beacons

The system we present is similar to many others in this field.
All smartphone localization system operates with hybrid measurement model.

// SLAM system
// including loop closing, relocalization and map reuse
// for
// smartphone localization
// with hybrid measurement model
// and main focus on magnetic field measurments.

We want to implement magnetic field measurements in localization *framework*.

Magnetic field based positioning consists of two global processes: information collection or mapping and information extracting or localization.

During mapping stage of magnetic field localization, we are constantly accumulating error. We have no tools for error correction because IMU and magnetic field provide both only relative information, and for error correction we need prior spatial information. The prior information can be collected from other sensors (e.g. beacons, such as WiFi and BLE beacons), information can be human input of location, the prior locatin can be obtained with camera based place recognition. The most interesting approach is to utilise the information we have in our conditions: previous measurements from magnetic mapping. That is the reason why we need loop closure features for robust magnetic field mapping.

The magnetic field in buildings is not stable and changing with time. Even after measurements collected, it is important to update map sequentially. The updates can be done by collecting and processing localization data from all system users.
This approach is called crowdsoursing in related literature. This is why place recognition, map updates and loop closures are the main parts of magnetic field navigation.



// We may assume that information of magnetic field is given and perform only localization task, which is simpler and requires only extraction fingerprint data from map and any king of localization model (particle filter).

In most existing papers,

Different from existing work, we want to re-estimate or post-process all distance and orientations
after measurements with information about previous steps are collected.
This is called the loop closure process in SLAM literature <<orb-slam>>, <<orb-slam2>>.

// end::background_and_ps[]

=== Objectives

// tag::objectives[]

// Описание цели и определения дипломного проекта и краткое изложение ряда конкретных целей, с помощью которых ваша работа предназначена для достижения целей. Сформулируйте гипотезы, которые нужно проверить, или технологию, которую необходимо разработать.

We perform this research to create an indoor positioning system with special features.
The objective of this research is to develop all algorithms needed to obtain these features.

We can write the criteria for the positioning system we develop.

.Criteria for the proposed system:
// * can be implemented locally
* no prior map is available
** the system can work as SLAM system (real-time navigation with no prior map)
* no special hardware for operation except smartphones
** positioning accuracy enough for operation (1-2m is the usual accuracy in this conditions)
// * cost, complexity, accuracy, time of development
* the system aggregate data from many sources (crowd-source) and improves the localization accuracy

// bad formulation
We formulate several hypotheses we evaluate during research:

.Hypotheses:
. The technology of magnetic field navigation can be implemented and fine-tuned for indoor croudsource SLAM
. The data from magnetic field and inertial sensors is enough for running SLAM
. The croudsource system satisfies the system optimality conditions and improve the accuracy

The hypothese #2 was not proved in existing systems. For most system, additional prior knowledge is needed. This is more the scientific interest to prove this hypotese.

Two other hypoteses are more the engineering questions. We have to compare performance and robustness of our algorithm and systems to other state of the art approaches. However for our problem statement, there is no much systems that have achieved any reasonable accuracy (1-2m). So we aim to achieve the accuracy that can be compared to other methods only.


// end::objectives[]


=== Literature review
//* A preliminary literature review/information retrieval that provides context and related literature for the thesis project.

//tag::literature-review[]

For the positioning technologies comparison, we may refer to the paper of <<Lymberopoulos>> which provides evaluation and comparison of different indoor location technologies and covers the almost full landscape of them.

While the information about technologies itself is more or less clear. What performance we can reach with given technology? What is the best approach to work with the given technology?

The answer to some questions is simple. The best accuracy is achieved with the biggest database and computational power. But for realistic implementation this is not good enough.
The similar approach is to merge all information available in current location and time. The problem again is that how to localize when there is no information available at the current state. The answer is to use the correspondences between previous and future information, to reconstruct the current information.
This formulation can be related to the classical SLAM formulation, even if some parts are different.

Different from existing work, we want to re-estimate or post-process all distance and orientations
after measurements with information about previous steps are collected.
This is called the loop closure process in SLAM literature <<orb-slam>>, <<orb-slam2>>.
In fingerprinting literature, there is low number of researches working with relocalization and loop closures.
We have to recursively post-process existing data, which has to give us better localization during mapping, and thus better map for future localization.
// WARNING: present sources here

If magnetic map is not given, the model training can be done by manually collection measurements and marking the locations by special trainers, then the localization model can be generated.

Why magnetic field localization is not a SLAM?
SLAM techniques build a map of an unknown environment and localize the
sensor in the map with a strong focus on real-time operation <<orb-slam>>.
With magnetic field localization, in every new point we obtain only local information, which is not enough for real-time operation. The difference between camera-based and magnetic fingerprints based localization is significant.
Because of this fact, magnetic field localization can't operate independently in unknown conditions and can't be considered as SLAM. Nevertheless, we may introduce special aspects of SLAM system to magnetic field localization for better robustness.

// For real-time operation we have to develop system that will return information of location given the measurements.
The usual camera-based SLAM has the ability to automatically close loops, which means the correction of the accumulated error in exploration after we detect the sensor has returned to a mapped area.

// We need same loop closure features for magnetic field mapping.

// As the place recognition is a key module of a usual SLAM system to close loops, we want to have same algorithms in magnetic field based systems. When we detect the sensor has returned to a mapped area and correct the accumulated error in exploration.

During mapping stage of magnetic field localization, we are constantly accumulating error. We have no tools for error correction because IMU and magnetic field provide both only relative information, and for error correction we need prior spatial information. The prior information can be collected from other sensors (e.g. beacons, such as WiFi and BLE beacons), information can be human input of location, the prior location can be obtained with camera based place recognition. The most interesting approach is to utilize the information we have in our conditions: previous measurements from magnetic mapping. That is the reason why we need loop closure features for robust magnetic field mapping.

The magnetic field in buildings is not stable and changing with time. Even after measurements collected, it is important to update map sequentially. The updates can be done by collecting and processing localization data from all system users.
This approach is called crowdsoursing in related literature. This is why place recognition, map updates and loop closures are the main parts of magnetic field navigation.


In <<maloc, Maloc>> introduced magnetic field based localization system: particle filter which
includes a dynamic step length estimation method.
Human step length prediction can be introduced in the localization model, but this is only a part of
information possible for given conditions.

Several researches states that the best performance is achieved in multi-sensor or hybrid localization steps.
And for walking human localization we may consider a dynamic step length estimation method proposed in <<maloc>>.


// hybrid measurement model
//
// independent from phone orienta-
// tion

// todo implement
// Mobile Positioning Using Wireless Networks
// 3-Axis Magnetic Field Mapping and Fusion for Indoor Localization

// A Realistic Evaluation and Comparison of Indoor Location

// end::literature-review[]

=== Methodology /  theoretical framework
//* A statement of the methodology for the thesis project that defines the specific design of the procedures, data collection, analysis, and (or) interpretation. Illustrate how the method you have chosen best allows you to fulfill the purpose of the thesis project.
// include::src/methodology.adoc[]


// tag::methodology[]
// design of the procedures, data collection, analysis, and (or) interpretation.

With the development of microelectromechanical systems(MEMS), a few MEMS-based sensors have been built and incorporated into smartphones: accelerometers, gyroscopes, magnetometers, etc. These sensors can be used to provide information on the user’s actions. Pedestrian dead reckoning (PDR) is a relative navigation technique that uses these sensors.

We propose a PDR-based indoor positioning method, that integrates RSSI and magnetic field measurements with indoor environment map constraints by using particle filters.

For proper evaluation of algorithm performance, we have to obtain ground truth data.
There are several methods of doing this process:

. usage of verified tracking / positioning system with better accuracy
. manual recording of position, using the constant measured track as ground truth (straight line, circle, rotation)
. usage of public dataset with available ground truth

In our conditions, we choose to first use the dataset of IMU & MEMS and ground truth measurements provided by <<rudacop, "RuDaCoP: The Dataset for Smartphone-based Intellectual Pedestrian Navigation">>.

Then we aim to develop a smartphone data-logging app for dataset collection to run the algorithm on smartphone data.

// end::methodology[]

// tag::techniques[]

The methods we are planning to use are Graph-SLAM, Gaussian process latent variable models (<<gplvm,GP-LVM>>), magnetic  fingerprinting (<<Grand20123AxisMF, E. Grand and S. Thrun. 3-axis magnetic field mapping and fusion>>).

// end::techniques[]

// === Techniques
// //* A description of techniques to be used for the development of the thesis product, including specific software tools, programming languages, or other appropriate techniques.
// include::src/tech.adoc[]

// === Timeline
// //* A work plan that outlines the sequencing, flow, and timeline of the thesis project.
// include::src/project-plan.adoc[]

// === Innovation impact
// //* A statement of potential impacts on innovation, research, and education and their relationship to the problem is proposed.
// include::src/innovation-research.adoc[]


// == Notes
//
// // tag::chapter-working-notes[]
//
// // include::draft/notes.adoc[tag='ch1']
//
// // end::chapter-working-notes[]
=== Conclusions
// CONCLUSIONS

.from articlexia

// 3-Axis Magnetic Field Mapping and Fusion for Indoor Localization
// sampling from map
Those positions describe a mesh, on which we have
mapped the magnetic field. We populate the rest of the map
by linear interpolation from the mesh.

VII. C ONCLUSION
We presented a real time indoor localization method that
utilizes a single 3-axis magnetometer to estimate the location
of a handheld device. Using an online particle filter, we
achieved localization accuracy of 0.7 meters in position and
25 degrees in orientation for the simple straight line
trajectory. The localization of the circle trajectory gave a
slightly higher instantaneous position error (up to 1.2m) and
orientation error (up to 40°). Those results must be
interpreted with care because better results would easily be
obtained by using an a posteriori position estimate. They
demonstrate that indoor localization based solely on
magnetometer and accelerometer data is possible.

The main limitation of this indoor localization approach is
the necessity of creating magnetic field maps. Therefore, we
presented a fast 2D mapping technique and demonstrated it
in a square room. Generalization of the technique to non-
square rooms with obstacles (Fig. 8) is possible by replacing
the lines
and
by a list of segments. The energy
minimization algorithm can then be modified by replacing
the constraints on the lines’ intersections by constraints on
the segments’ intersections.

// filters combine
There are plenty of principles that dictate how to combine the outputs of these filters to one position estimate, for instance merging the states as in interactive multiple models (IMM), pruning as in adaptive forgetting through multiple models (AFMM), or motion parameter estimation as in hidden Markov models (HMM) (see [53] for an overview). A performance lower bound when the number of states increases is the function of true mobility

====
Location in wireless networks is of increasing importance for
safety, gaming, and commercial services. There are plenty of
measurements available today, ranging from signal arrival times
to maps of received power. We have demonstrated how funda-
mental the FIM for each measurement is to assess possible loca-
tion performance. As one illustration, the FCC positioning
requirements are transformed to requirements on sufficient
information. Thereby, it is possible to investigate whether specif-
ic sensor configurations would provide acceptable accuracy. The
information is additive, so several measurements increase infor-
mation. The information concept can also handle less conven-
tional measurements, such as digital propagation prediction
maps and road maps. A practical question is whether there is an
algorithm that attains the position error lower bound and if it is
possible to implement this algorithm in practice. This, of course,
depends from case to case, and we have briefly pointed out algo-
rithms of particular interest.
A short road path to implement a positioning system is as
follows.

\item Collect the available measurements in Table 2.
\item Compute the static CRB using (3) or using (4a) in the
Gaussian case.
\item Compare this to the FCC requirements in Table 1.
\item If these are not satisfied, continue with step 5. Otherwise,
evaluate algorithms based on one of the criteria in Table 3
using one of the algorithms in Table 4. If these algorithms
do not yield a satisfactory result, continue with step 5.
\item Select a motion model in Table 7.
\item Compare the CRB to the FCC requirements in Table 8.
\item If these are satisfied, try to find an algorithm in Table 9
that gives satisfactory result. If this fails, try to change the
system configuration to obtain better measurements, or
equip the MS with more sensors.
Briefly, the results indicate that the FCC requirement may be
reached using a snapshot localization approach in a most favor-
able situation, including LOS and a good estimator. The accura-
cy is increased an order of magnitude with filtering and
potentially another order of magnitude with motion sensors.
====


// tag::timeline[]
=== Timeline

.Project timeline
|====
|thesis proposal | 10-12-2020
|formal derivation of algorithm | 25-12-2020
|algorithm performance evaluation on existing dataset | 12-01-2021
|prototyping the mobile app for dataset collection| 18-01-2021
|dataset collection & data processing | 25-01-2021
|performance evaluation on collected data| 01-02-2021
|results formulation|
|====
// end::timeline[]



=== References
//* A list of references.

// tag::references[]

// . S. Walden, “The “indoor generation” and the health risks of spending more time inside,” 05 2018.
// . R. Mautz, “Indoor positioning technologies,” 2012.
// . W. Sakpere, M. A. Oshin, and N. Mlitwa, “A state-of-the-art survey of indoor positioning and navigation systems and technologies,”South African Computer Journal,vol. 29, pp. 145–197, 2017.
.  [[book_Indoor_positioning]]M. Kjærgaard, “Indoor positioning with radio location fingerprinting,” 04 2010.
https://arxiv.org/pdf/1004.4759.pdf
. [[brena]]R. F. Brena, J. P. Garc ́ıa-V ́azquez, C. E. Galv ́an-Tejada,D. Mu ̃noz-Rodriguez, C. Vargas-Rosales, and J. Fang-meyer, “Evolution of indoor positioning technologies: A survey,”Journal of Sensors, Mar 2017.
. [[Infsoft]]Infsoft, “Indoor positioning and services white paper,”2019.
. [[Bernard]]R. Bernard, “Indoor positioning systems,”Security Industry Association, 2017.
. [[IndoorAtlas]]IndoorAtlas / Vanson Bourne, “A 2016 global research report on the indoor positioning market,” p. 6, 2016.
. [[Gallagher]]B. Li, T. Gallagher, C. Rizos, and A. Dempster, “Using geomagnetic field for indoor positioning,”Journal of Applied Geodesy, vol. 7, 11 2013.
. [[Orientation-aided]]L. Hou, Y. Li, Y. Zhuang, B. Zhou, G. Tsai, Y. Luo, and N. El-Sheimy, “Orientation-aided stochastic magnetic matching for indoor localization,”IEEE Sensors Journal,vol. 20, no. 2, pp. 1003–1010, 2020.
https://www.semanticscholar.org/paper/WiFi-Aided-Magnetic-Matching-for-Indoor-Navigation-Li-Zhuang/ff8e0b25ac3246a2a4f9efaa330276e07779bbeb
. [[Alliance]]I. Alliance, “ILA system architecture release 1.0,”openmobilealliance.
// . Indoor navigation market review by iBecom, June 4 2015
// . Geofencing market guide, Justin Croxton, Sept 26 2019
. [[BLE_loc]]Thaljaoui, A., Val, T., Nasri, N., & Brulin, D. (2015). BLE localization using RSSI measurements and iRingLA. 2015 IEEE International Conference on Industrial Technology (ICIT). doi:10.1109/icit.2015.7125418
. [[Lymberopoulos]]Lymberopoulos, Dimitrios & Liu et Al (2015). A Realistic Evaluation and Comparison of Indoor Location Technologies: Experiences and Lessons Learned. 10.1145/2737095.2737726.
. [[survey]]Müller, P., Raitoharju, M., Ali-Löytty, S. et al. A survey of parametric fingerprint-positioning methods. Gyroscopy Navig. 7, 107–127 (2016). https://doi.org.proxylib.skoltech.ru:2050/10.1134/S2075108716020061
// https://www.scribbr.com/category/dissertation/
. [[Bayesian_loc]]Bayesian Indoor Location Algorithm Based on RSSI
PENG Yu-xu, YANG Yan-hong (School of Computer & Communication Engineering, Changsha University of Science & Technology, Changsha 410114, China)
http://en.cnki.com.cn/Article_en/CJFDTotal-JSJC201210075.htm
. [[thrun]]Grand, E. and S. Thrun. “3-Axis magnetic field mapping and fusion for indoor localization.” 2012 IEEE International Conference on Multisensor Fusion and Integration for Intelligent Systems (MFI) (2012): 358-364. https://www.semanticscholar.org/paper/3-Axis-magnetic-field-mapping-and-fusion-for-indoor-Grand-Thrun/da91e43d72afe677718f769ddd2b3ae86d7bc3fb
. [[maloc]]Xie, Hongwei & Gu, Tao & Tao, Xianping & Ye, Haibo & Lu, Jian. (2015). A Reliability-Augmented Particle Filter for Magnetic Fingerprinting Based Indoor Localization on Smartphone. IEEE Transactions on Mobile Computing. 15. 1-1. 10.1109/TMC.2015.2480064.
. [[articleXia]] Hao  Xia,  Jinbo  Zuo,  Shuo  Liu,  and  Yanyou  Qiao. Indoor  localization  on smartphones using built-in sensors and map constraints. IEEE Transactions on Instrumentation and Measurement, PP:1–10, 08 2018.[2]  Min Zhang,  Ling Pei,  and Xiaotie Deng.
. [[r7809951]] Graph slam-based crowdsourcing framework for indoor wi-fi fingerprinting. In2016 Fourth International Conference on Ubiquitous Positioning, Indoor Navigation and Location Based Services (UPINLBS), pages 61–67, 2016.
. [[gplvm]] Brian Ferris, Dieter Fox, and Neil Lawrence.  Wifi-slam using gaussian process latent variable models.  volume 7, pages 2480–2485, 01 2007.[4]
. [[Grand20123AxisMF]] E. Grand and S. Thrun. 3-axis magnetic field mapping and fusion for indoor localization.2012 IEEE International Conference on Multisensor Fusion and Integration for Intelligent Systems (MFI), pages 358–364, 2012.
. [[r6827640]] X. Zhang, Y. Jin, H. Tan, and W. Soh. Cimloc: A crowdsourcing indoor dig-ital map construction system for localization.  In2014 IEEE Ninth International Conference on Intelligent Sensors, Sensor Networks and Information Processing (ISSNIP), pages 1–6, 2014
. [[rudacop]] Bayev, A. et al. “RuDaCoP: The Dataset for Smartphone-based Intellectual Pedestrian Navigation.” 2019 International Conference on Indoor Positioning and Indoor Navigation (IPIN) (2019): 1-8.
. [[orb-slam]] Mur-Artal, Raul & Montiel, J. & Tardos, Juan. (2015). ORB-SLAM: a versatile and accurate monocular SLAM system. IEEE Transactions on Robotics. 31. 1147 - 1163. 10.1109/TRO.2015.2463671.
. [[orb-slam2]] Galvez-Lopez, Dorian & Tardos, Juan. (2012). Bags of Binary Words for Fast Place Recognition in Image Sequences. Robotics, IEEE Transactions on. 28. 1188-1197. 10.1109/TRO.2012.2197158.


// end::references[]
