= Construct probabilistic framework for smartphone localisation in zero infrastructure conditions
// :sectnums:




[abstract]


dbsseeb
// [abstract!]


// [lead]
== Documentation Abstract


Problem: no effecient algorithm for smartphone localisation in conditions with:

* no/low number hardware (beacons) available
* available measurements are noisy
* map/measurements are changing over time

Algorithm effeciency:

- accuracy
- computational difficulty (we may compare relative only by the factor of space size)

Sota accuracy: 1m for magnetic fingerprinting, 1-5 m for wifi RSSI, 0.1 m for tdoa and other special techniques - requirement is multiple beacons in field of view
Limits: real needed limit approximately 0.3m to 1m.
Higher accuracy requires special hardware and environment conditions, not important in research.

Cannot be achieved by ordinary Rssi

zero infrastructure localisation can be done with smartphone's imu, magnetometer and wifi RSSI. We want to utilize magnetic field fingerprinting data for improving accuracy in locations with no ability to use wi-fi RSSI data. current methods show accuracy 1m and 15 degrees.
We want to reach same accuracy and define a scalable framework for indoor localisation and mapping.


include::algorithm.adoc[]


=== Progress by now

. Some part of data generation
. Random trajectories generation using Bezier curves + Gaussian noise

What to do
. What is a particle filter
. How to construct the pdf to sample from?
- we find similar signal. We know orientation and don't know distance (speed). We may want to find similar points in multiple directions (2dim»1 dim case)
. Support vector machine is connected with particle filter?
. We construct a continuous approximation for k neighborhood clustering, what solutions are known?
. How-to apply hmc and MCMC for reversible localisation.
- HMC allows to explore high dimensional space. We may represent our task as continious/probability density function approximation and traverce over this space
- We have to set exploration speed low. Possibly the usual hmc is not applicable for implementation. Check what are conditions for Markov chain in this model


// rssi
// fingerprinting
// collect database of measurements

// measurement -> coordinate
// offline map updates, relocalization
// methods in use
// ideas to implementdeas
// Bayesian framework
// Markov chain model, possibly HMC
// approximation method to perform Monte Carlo approximation
// literature review
// wifi rssi


:stem: latexmath

=== lecture 9 data association

problem of data association,
the distribution of correspondences of observations to states can't be calculated explicitly (?)
we need some assumptions for data association, we do iterative updates of correspondences data.

[.lead]
calculating online

- only the last position matters
history of correspondences only depend on the last estimate

previous correspondences were correct - assumption (conditional independence from previous correspondences)

stem:[c_t = {c_t^1, c_t^2, ...}]


batch optimization - evaluation of previous correspondences back in time


    IF there is no landmarks, how to create landmarks from measurements??
    clustering of data based on signal similarity, graph clustering, corridor == edge, splitting into parts

    similarity of trajectories, similarity of measurements (cross-covariance)

IMPORTANT: data association

$p(z | c^i_t = new, y_t)$ threashold

We need to estimate what data can be used to construct an auxilary localization point.
From data, we extract by similarity long enough traclets & measurements.


map processing
* We extract straight lines from the data with running mean and some offset.
* We classify and try to get similarities with the loop closure

localization with given map:: particles filter.
  from current location sample proposal points, create smooth trajectories based on points
  compare similarity between meSUREMENTS

map construction by given beacon data::
  * in locations where beacon data is available - traditional slam (ekf, pf)
  * when no data is available, use the markov graph map of building location


building location map construction::
  * markov graph map combine spatial data of building structure (doors, corridors..) and landmarks or existing data to location association
  * graph of the building considered as given. we construct it from the building map as the non-directional graph in traditional format. we additionally assign weights to the graph edges, given the restriction of *markovian* feature of this graph
